// Write by Kuanlan (Kuanlan@outlook.com)
// Minimum perfect hash function for Lua language binding.
// This source file is generated by code generator.
// Don't modify this file directly, please modify the generator configuration.

#pragma once

namespace LuaSTGPlus {
    enum class Particle2DMember {
        __NOT_FOUND = -1,
        a = 1,
        ax = 2,
        ay = 3,
        b = 4,
        color = 5,
        extra1 = 6,
        extra2 = 7,
        extra3 = 8,
        g = 9,
        omiga = 10,
        r = 11,
        rot = 12,
        sx = 13,
        sy = 14,
        timer = 15,
        vx = 16,
        vy = 17,
        x = 18,
        y = 19,
    };
    Particle2DMember MapParticle2DMember(const char* key);
}

namespace LuaSTGPlus {
    enum class Particle3DMember {
        __NOT_FOUND = -1,
        a = 1,
        ax = 2,
        ay = 3,
        az = 4,
        b = 5,
        color = 6,
        extra1 = 7,
        extra2 = 8,
        extra3 = 9,
        extra4 = 10,
        g = 11,
        ox = 12,
        oy = 13,
        oz = 14,
        r = 15,
        rx = 16,
        ry = 17,
        rz = 18,
        sx = 19,
        sy = 20,
        timer = 21,
        vx = 22,
        vy = 23,
        vz = 24,
        x = 25,
        y = 26,
        z = 27,
    };
    Particle3DMember MapParticle3DMember(const char* key);
}

namespace LuaSTGPlus {
    enum class TexParticle2DMember {
        __NOT_FOUND = -1,
        a = 1,
        ax = 2,
        ay = 3,
        b = 4,
        color = 5,
        extra1 = 6,
        extra2 = 7,
        extra3 = 8,
        g = 9,
        h = 10,
        omiga = 11,
        r = 12,
        rot = 13,
        sx = 14,
        sy = 15,
        timer = 16,
        u = 17,
        v = 18,
        vx = 19,
        vy = 20,
        w = 21,
        x = 22,
        y = 23,
    };
    TexParticle2DMember MapTexParticle2DMember(const char* key);
}

namespace LuaSTGPlus {
    enum class TexParticle3DMember {
        __NOT_FOUND = -1,
        a = 1,
        ax = 2,
        ay = 3,
        az = 4,
        b = 5,
        color = 6,
        extra1 = 7,
        extra2 = 8,
        extra3 = 9,
        extra4 = 10,
        g = 11,
        h = 12,
        ox = 13,
        oy = 14,
        oz = 15,
        r = 16,
        rx = 17,
        ry = 18,
        rz = 19,
        sx = 20,
        sy = 21,
        timer = 22,
        u = 23,
        v = 24,
        vx = 25,
        vy = 26,
        vz = 27,
        w = 28,
        x = 29,
        y = 30,
        z = 31,
    };
    TexParticle3DMember MapTexParticle3DMember(const char* key);
}

