
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    set(CMAKE_SYSTEM_NAME Darwin)
endif()
if(NOT CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(CMAKE_SYSTEM_NAME Darwin)
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
endif()
set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE INTERNAL "")

execute_process(
    COMMAND brew --prefix llvm@20
    OUTPUT_VARIABLE LLVM_DIR
)

string(STRIP ${LLVM_DIR} LLVM_DIR)

set(CMAKE_FIND_ROOT_PATH ${LLVM_DIR})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

set(CMAKE_C_COMPILER ${LLVM_DIR}/bin/clang)
set(CMAKE_CXX_COMPILER ${LLVM_DIR}/bin/clang++)

set(CMAKE_LINKER_TYPE LLD)

set(CMAKE_C_COMPILER_TARGET x86_64-apple-darwin)
set(CMAKE_CXX_COMPILER_TARGET x86_64-apple-darwin)

