// Write by Kuanlan (Kuanlan@outlook.com)
// Minimum perfect hash function for Lua language binding.
// This source file is generated by code generator.
// Don't modify this file directly, please modify the generator configuration.

#pragma once

namespace LuaSTGPlus {
    enum class Particle2DMember {
        __NOT_FOUND = -1,
        a = 1,
        accel = 2,
        angle = 3,
        ax = 4,
        ay = 5,
        b = 6,
        color = 7,
        extra1 = 8,
        extra2 = 9,
        extra3 = 10,
        g = 11,
        omiga = 12,
        pos = 13,
        r = 14,
        rot = 15,
        scale = 16,
        speed = 17,
        sx = 18,
        sy = 19,
        timer = 20,
        vel = 21,
        vx = 22,
        vy = 23,
        x = 24,
        y = 25,
    };
    Particle2DMember MapParticle2DMember(const char* key);
}

namespace LuaSTGPlus {
    enum class Particle3DMember {
        __NOT_FOUND = -1,
        a = 1,
        accel = 2,
        angle = 3,
        ax = 4,
        ay = 5,
        az = 6,
        b = 7,
        color = 8,
        extra1 = 9,
        extra2 = 10,
        extra3 = 11,
        extra4 = 12,
        g = 13,
        ox = 14,
        oy = 15,
        oz = 16,
        pos = 17,
        r = 18,
        rx = 19,
        ry = 20,
        rz = 21,
        scale = 22,
        speed = 23,
        sx = 24,
        sy = 25,
        timer = 26,
        vel = 27,
        vx = 28,
        vy = 29,
        vz = 30,
        x = 31,
        y = 32,
        z = 33,
    };
    Particle3DMember MapParticle3DMember(const char* key);
}

namespace LuaSTGPlus {
    enum class TexParticle2DMember {
        __NOT_FOUND = -1,
        a = 1,
        accel = 2,
        angle = 3,
        ax = 4,
        ay = 5,
        b = 6,
        color = 7,
        extra1 = 8,
        extra2 = 9,
        extra3 = 10,
        g = 11,
        h = 12,
        omiga = 13,
        pos = 14,
        r = 15,
        rot = 16,
        scale = 17,
        speed = 18,
        sx = 19,
        sy = 20,
        timer = 21,
        u = 22,
        v = 23,
        vel = 24,
        vx = 25,
        vy = 26,
        w = 27,
        x = 28,
        y = 29,
    };
    TexParticle2DMember MapTexParticle2DMember(const char* key);
}

namespace LuaSTGPlus {
    enum class TexParticle3DMember {
        __NOT_FOUND = -1,
        a = 1,
        accel = 2,
        ax = 3,
        ay = 4,
        az = 5,
        b = 6,
        color = 7,
        extra1 = 8,
        extra2 = 9,
        extra3 = 10,
        extra4 = 11,
        g = 12,
        h = 13,
        ox = 14,
        oy = 15,
        oz = 16,
        pos = 17,
        r = 18,
        rx = 19,
        ry = 20,
        rz = 21,
        scale = 22,
        speed = 23,
        sx = 24,
        sy = 25,
        timer = 26,
        u = 27,
        v = 28,
        vel = 29,
        vx = 30,
        vy = 31,
        vz = 32,
        w = 33,
        x = 34,
        y = 35,
        z = 36,
    };
    TexParticle3DMember MapTexParticle3DMember(const char* key);
}

