name: CMake on multiple platforms

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_VERSION: 4.6
      CCACHE_BASEDIR: ${GITHUB_WORKSPACE}
      CCACHE_DIR: ${GITHUB_WORKSPACE}/.ccache
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_MAXSIZE: 400M

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, windows-latest, macos-14]
        # build_type: [Release]
        # build_type: [Release, RelWithDebInfo, Debug]
        target_arch:
          - main: x86_64
            main_win: AMD64
            rev: westmere
            rev_win: SSE4.2
          - main: x86_64
            main_win: AMD64
            rev: haswell
            rev_win: AVX2
          - main: arm64
            main_win: ARM64
            rev: armv8.2-a
            rev_win: armv8.2
        exclude:
          - os: macos-14
            target_arch:
              rev_win: AVX2

    steps:
    - name: Configure Linux (arm)
      if: ${{ runner.os == 'Linux' && matrix.target_arch.main == 'arm64' }}
      run: |
        sudo dpkg --add-architecture arm64
        sudo sed -i "/Components: /a Architectures: amd64" /etc/apt/sources.list.d/ubuntu.sources
        # sudo sed -Ei 's/deb (\w)/deb [arch=amd64] \1/g' /etc/apt/sources.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble main restricted"                                | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-updates main restricted"                        | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble universe"                                       | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-updates universe"                               | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble multiverse"                                     | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-updates multiverse"                             | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse"  | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-security main restricted"                       | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-security universe"                              | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-security multiverse"                            | sudo tee -a /etc/apt/sources.list > /dev/null
        sudo apt update
        sudo apt install \
          libssl-dev:arm64 gcc-14-aarch64-linux-gnu libstdc++-14-dev-arm64-cross binutils-aarch64-linux-gnu \
          libx11-dev:arm64 libwayland-dev:arm64
    - name: Configure Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main"     | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main" | sudo tee -a /etc/apt/sources.list > /dev/null
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt update
        sudo apt install cmake llvm-20 clang-20 lld-20 clang-tools-20 \
          ninja-build mesa-utils mesa-common-dev libxext-dev libasound2-dev \
          libpipewire-0.3-dev libaudio-dev libjack-dev libsndio-dev libssl-dev \
          libasound2-dev libpulse-dev libpulse-mainloop-glib0 libglib2.0-dev libxkbcommon-dev
    - name: Configure Windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        Install-Module -Name VCVars -Confirm:$false -Force
        git config --system core.longpaths true
        (vcvars ${{ matrix.target_arch.main_win }}).GetEnumerator()
        | Foreach { "$($_.Key)=$($_.Value)" >> "$env:GITHUB_ENV" }
    - name: Configure macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install llvm@20 dylibbundler lld
        echo SDKROOT=$(xcrun --sdk macosx --show-sdk-path) >> $GITHUB_ENV

    - name: Download ccache
      id: ccache
      shell: cmake -P {0}
      run: |
        set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v$ENV{CCACHE_VERSION}/${{ runner.os }}.tar.xz")
        file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)
    - name: Add ccache to PATH
      run: echo "$(pwd)" >> $GITHUB_PATH
    
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache C++ packages
      id: cache-cpp
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build/cpm-cache
        key: ${{ runner.os }}-${{ matrix.target_arch.rev_win }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.target_arch.rev_win }}-cpm-

    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")

    - name: ccache cache files
      id: ccache_cache
      uses: actions/cache@v4
      with:
        path: .ccache
        key: ${{ runner.os }}-${{ matrix.target_arch.rev_win }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.target_arch.rev_win }}-ccache-

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/toolchain/${{ runner.os }}-${{ matrix.target_arch.main }}.cmake
        -DCMAKE_BUILD_TYPE=Release
        -DTARGET_ARCH_REV="${{ matrix.target_arch.rev }}"
        -DTARGET_ARCH_REV_WIN="${{ matrix.target_arch.rev_win }}"
        -DCPM_SOURCE_CACHE=${{ github.workspace }}/build/cpm-cache
        -G Ninja

    - name: Build With CMake
      run: >
        cmake --build ${{ github.workspace }}/build --config Release --target LuaSTG

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin-${{ runner.os }}-${{ matrix.target_arch.main }}-${{ matrix.target_arch.rev_win }}
        path: |
          build/bin
        retention-days: 7
