name: CMake on multiple platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    env:
      CCACHE_VERSION: 4.7.3
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_DIR: ${{ github.workspace }}/build/.ccache
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_MAXSIZE: 400M

    strategy:
      fail-fast: false

      matrix:
        config:
        - os: ubuntu-24.04
          rev: westmere
          rev_win: SSE4.2
        - os: ubuntu-24.04
          rev: haswell
          rev_win: AVX2
        - os: ubuntu-24.04-arm
          rev: armv8-a
          rev_win: armv8
        - os: windows-latest
          rev: westmere
          rev_win: SSE4.2
        - os: windows-latest
          rev: haswell
          rev_win: AVX2
        - os: windows-11-arm
          rev: armv8-a
          rev_win: armv8
        - os: macos-15-intel
          rev: westmere
          rev_win: SSE4.2
        - os: macos-15
          rev: armv8.2-a
          rev_win: armv8.2
        # build_type: [Release]
        # build_type: [Release, RelWithDebInfo, Debug]

    steps:
    - name: Configure Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main"     | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb-src http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main" | sudo tee -a /etc/apt/sources.list > /dev/null
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt update
        sudo apt install cmake ninja-build llvm-20 clang-20 lld-20 clang-tools-20 \
          ccache mesa-utils mesa-common-dev libxext-dev libasound2-dev \
          libpipewire-0.3-dev libaudio-dev libjack-dev libsndio-dev libssl-dev \
          libpulse-dev libpulse-mainloop-glib0 libglib2.0-dev libxkbcommon-dev
    - name: Configure Windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install ccache
        Install-Module -Name VCVars -Confirm:$false -Force
        git config --system core.longpaths true
        (vcvars ${{ runner.arch == 'X64' && 'AMD64' || runner.arch }}).GetEnumerator()
        | Foreach { "$($_.Key)=$($_.Value)" >> "$env:GITHUB_ENV" }
    - name: Configure macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install llvm@20 dylibbundler lld ccache
        echo SDKROOT=$(xcrun --sdk macosx --show-sdk-path) >> $GITHUB_ENV
    
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache C++ packages
      id: cache-cpp
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build/cpm-cache
        key: ${{ runner.os }}-${{ matrix.config.rev_win }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.config.rev_win }}-cpm-

    - name: ccache cache files
      id: ccache_cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build/.ccache
        key: ${{ runner.os }}-${{ matrix.config.rev_win }}-ccache-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.config.rev_win }}-ccache-

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/toolchain/${{ runner.os }}-${{ runner.arch == 'X64' && 'x86_64' || 'arm64' }}.cmake
        -DCMAKE_BUILD_TYPE=Release
        -DTARGET_ARCH_REV="${{ matrix.config.rev }}"
        -DTARGET_ARCH_REV_WIN="${{ matrix.config.rev_win }}"
        -DCPM_SOURCE_CACHE=${{ github.workspace }}/build/cpm-cache
        -DGITHUB_ACTIONS=ON
        -G Ninja

    - name: Build With CMake
      run: >
        cmake --build ${{ github.workspace }}/build --config Release --target LuaSTG

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin-${{ runner.os }}-${{ runner.arch }}-${{ matrix.config.rev_win }}
        path: |
          build/bin
        retention-days: 7
